# Generated by Django 4.2 on 2023-04-16 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.TextField(max_length=300)),
                ('publication_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cover', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='BookMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book.bookdetail')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookmain')),
            ],
        ),
    ]
