# Generated by Django 4.2 on 2023-04-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='cover',
            field=models.CharField(choices=[('PAP', 'Paperback'), ('HAR', 'Hardcover')], max_length=3),
        ),
    ]
