# Generated by Django 4.2 on 2023-04-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookdetail_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmain',
            name='title',
            field=models.TextField(),
        ),
    ]
