# Generated by Django 4.2 on 2023-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookmain_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='publication_date',
            field=models.DateField(verbose_name='%y'),
        ),
    ]
